title: "ChenHuaying's Blog"
languageCode: "zh-CN"
baseurl: "http://chenhuaying.github.io"
disqusShortname: "chenhuaying"
copyright: "Copyright (c) 2015, chenhuaying; all rights reserved."
theme: "introj"
MetaDataFormat: "yaml"
canonifyurls: true
builddrafts: false
Paginate: 7
PaginatePath: paginator
disablePathToLower: true
hasCJKLanguage: true
permalinks:
  posts: /:year/:month/:day/:title/
Taxonomies:
  tag: "tags"
  category: "categories"
params:
  CopyrightHTML: "Copyright &#xA9; 2015 Chenhuaying. All Rights Reserved."
  GitHubUser: "chenhuaying"
  DateForm : "2006年01月02日"
  HeaderLine: "程序员一枚 | Linux Go C/C++ Python | Server"
  SidebarRecentLimit: 5
  Categories:
    - "感想随笔"
    - "技术文章"
    - "读书笔记"
    - "随时记录"
images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
